services:
  petradar-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pet-radar:latest
    container_name: PetRadarAPI
    ports:
      - 3000:3000
    environment:
      PORT: ${PORT}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_SERVICE: ${MAILER_SERVICE}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
      MAPBOX_TOKEN: ${MAPBOX_TOKEN}
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432            
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      APPINSIGHTS_CONNECTION_STRING: ${APPINSIGHTS_CONNECTION_STRING}
      REDIS_HOST: redis
      REDIS_PORT: 6379        
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - petRadar-network

  postgres:
    image: postgis/postgis:16-master
    container_name: PetFoundedDB
    ports:
      - 5436:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - postgres_data_db:/var/lib/postgresql/data
    networks:
      - petRadar-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: petRadar-redis
    ports:
      - 5437:6379
    volumes:
      - redis_data_db:/data
    networks:
      - petRadar-network

volumes:
  postgres_data_db:
  redis_data_db:

networks:          
  petRadar-network:
    driver: bridge