[Interface]
Address = 192.168.27.2
PrivateKey = qHjFFaeKn5XEdn25QKyaVheWF16D/XBylfmwosGhOXs=
ListenPort = 51820
DNS = 192.168.27.1

[Peer]
PublicKey = 8x6CFZZj7ecCP4XBo+ALyttTWT6qdPpjzerPMSiWLFE=
PresharedKey = SvlUd1rx41/Nc0VgzyFRMEd+eqP0FpB/1/ubnnfGgPc=
Endpoint = 20.94.202.170:51820
AllowedIPs = 0.0.0.0/0, ::/0
