github_username:  "{{vault_github_username}}"
github_password:  "{{vault_github_password}}"
postgres_db: "radardb"
shared_docker_network: "api-network"
postgres_password: "{{ vault_postgres_password }}"
shared_docker: "api-network"
vault_mapbox_token: "{{ vault_mapbox_token }}"
vault_mailer_email: "soniblast7@gmail.com"
vault_mailer_password: "ekiibzqjyodzbeng"
vault_appinsights_connection_string: "InstrumentationKey=ff4eeb6e-f6fe-4684-9fac-462a0427a02c;IngestionEndpoint=https://westus2-2.in.applicationinsights.azure.com/;LiveEndpoint=https://westus2.livediagnostics.monitor.azure.com/;ApplicationId=b65bcd80-e420-4409-a388-0d90dbd6d757"
